[book]
authors = ["Kody A Kantor"]
language = "en"
multilingual = false
src = "src"
title = "Kody's Blog"

[build]
create-missing = false

[output.html]
default-theme = "rust"
preferred-dark-theme = "rust"