baseUrl="https://kodykantor.github.io/"
languageCode = "en-us"
title = "a bird in the hand"
theme = "hugo-theme-bootstrap4-blog"
googleAnalytics = "UA-90522412-1"

[[menu.sidebar]]
  name = "GitHub"
  url = "https://github.com/kodykantor"

[[menu.sidebar]]
  name = "LinkedIn"
  url = "https://www.linkedin.com/in/kodykantor"

[params]
  author = "Kody Kantor"
  [params.sidebar]
    about = "Observations on software development, and other things"
